### ISSUE TITLE
Automatically generate shell auto-completion files

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#129]
**Description**

Starting from https://github.com/cloudskiff/driftctl/pull/127, it's a much better idea to automatically generate with cobra the auto-completion files for zsh, bash, and fish 

**Example**

https://github.com/spf13/cobra/blob/master/fish_completions.md

**Comment by wbeuil** [comment]
What do you mean by automatically ? As per cobra's doc, you will need to run `driftctl completion bash|zsh|fish|powershell` to have it. Is it what you had in mind ?

**Comment by sjourdan** [comment]
Yes, that could work well too! 

What I had in mind was either: 

- Terraform-style autocompletion installation from the CLI (close to your suggestion): https://www.terraform.io/docs/commands/index.html#shell-tab-completion
- Dumb-style generated files (from CI for example) in some folder in our source code (like ./completion), allowing users to choose which to install and how/where

**Comment by wbeuil** [comment]
Ok will try as per cobra's doc since I think it's more user-friendly to let our users choose which completion to use.

**Comment by eliecharra** [comment]
Terraform style installation looks nice 👍🏻 Maybe we could detect current shell and install only required completions with a single `driftctl install-completion` command

**Comment by wbeuil** [comment]
This is not quite the same cli library and thus not the same way how they approach how to install auto-completion.

Terraform uses https://github.com/mitchellh/cli library which uses internally https://github.com/posener/complete library to install the auto-completion. First, this last library doesn't covered `Powershell` auto-completion script, but second, the way it is designed, it installs all the auto-completion scripts depending on whether it finds shell config file or not (e.g. if it finds a `.bashrc`, a `.zshrc` and a fish config file, it will install all three of them) which I don't really find useful. And last, it is less configurable than what cobra gives us (e.g. cobra will output to stdout the actual completion script that you could change as you wish whereas posener/complete will simply type to your shell config file a command like `complete -C complete -o nospace -C /usr/local/Cellar/tfenv/2.0.0/versions/0.14.4/terraform terraform`).

On the contrary, what cobra does is outputting a completion script to stdout that you could simply redirect to where the completion script needs to be. And it supports `[bash|zsh|fish|powershell]` out of the box. The problem with what you suggest about `detecting current shell and install the only required completion script` is that it could be hard to determine where to redirect the script because depending on the shell and the config you use, it changes the folder of auto-completion. Basically I came across this problem yesterday where for OhMyZsh the completion folder is different than the basic zsh completion folder if you were not using it. 

Thus I'm more a fan of letting our user install the right completion file to where it needs to be depending on his shell config.

**Comment by eliecharra** [comment]
> is that it could be hard to determine where to redirect the script because depending on the shell and the config you use

Good point, ecosystem fragmentation is always a complicated to handle. I think we could find standard folders and or files to append our configuration, for example `~/.zshrc` and `~/.bashrc` are standard.

I'm good with both approach, but we as we are very early it makes a lot of sense to let our users integrate completion in their setup themselves. It will saves us a lot of time supporting and debugging a large variety of setup, we currently do not have the time to handle it. Typically the OhMyZsh case.

> Dumb-style generated files (from CI for example) in some folder in our source code (like ./completion), allowing users to choose which to install and how/where

So just to be sure I get it, we are going this way ? Btw I'm not a fan of putting generated artifact from CI in our VCS, maybe it makes more sense to put them as release attachment beside binaries.

**Comment by wbeuil** [comment]
Just to make it clearer, let me 2 min to push a PR in draft, you will understand what it means.

But TLDR it is not generated by our CI, you will need to type `driftctl completion zsh > redirect/folder/completion` in my case.

**Comment by moadibfr** [comment]
> So just to be sure I get it, we are going this way ? Btw I'm not a fan of putting generated artifact from CI in our VCS, maybe it makes more sense to put them as release attachment beside binaries.

I like more the idea to have drifctl generate the completion file on demand i think.

> it installs all the auto-completion scripts depending on whether it finds shell config file or not (e.g. if it finds a .bashrc, a .zshrc and a fish config file, it will install all three of them) which I don't really find useful. 

maybe we could do something like `driftctl install-completion zsh[,bash,fish]` ? This way user could install what he needs.

> Good point, ecosystem fragmentation is always a complicated to handle. I think we could find standard folders and or files to append our configuration, for example ~/.zshrc and ~/.bashrc are standard.

Yeah I think that for most of them there are standard place easy to find to output the completion

**Comment by eliecharra** [comment]
> But TLDR it is not generated by our CI, you will need to type driftctl completion zsh > redirect/folder/completion in my case.

Sounds great 👍🏻
