### ISSUE TITLE
Make disable version check more flexible 

### ISSUE THREAD

**Issue by eliecharra** [cloudskiff/driftctl#162]
**Description**
Let's make DCTL_NO_VERSION_CHECK active whatever its value, as long as the env variable is defined we should disable version check.

**Comment by sshota0809** [comment]
Hello @eliecharra, I'm so interested in and excited by this awesome tool!
So if possible I would like to contribute it and deal with this issue.

Let me make sure what you mean before I start to deal with this issue.
Do you mean it's possible that any string is defined as `DCTL_NO_VERSION_CHECK` ?
e.g.) true, foo, bar

If so, I plan to modify source code so that it check if `os.Getenv("DCTL_NO_VERSION_CHECK")` is nil or not.

Thank you for looking my comment!

**Comment by eliecharra** [comment]
Hi @sshota0809 !
Thanks a lot for your interest in driftctl, and thanks for asking more details on this one.

> Do you mean it's possible that any string is defined as DCTL_NO_VERSION_CHECK ?
e.g.) true, foo, bar

That's exactly the idea yes 👍🏻 

> If so, I plan to modify source code so that it check if os.Getenv("DCTL_NO_VERSION_CHECK") is nil or not.

You can use golang native method : https://golang.org/pkg/os/#LookupEnv

```go
_, isPresent := os.LookupEnv("DCTL_NO_VERSION_CHECK")
```

Don't forgot to update according tests in consequence 😉 

Can't wait to see your PR 😃

**Comment by sshota0809** [comment]
@eliecharra 
Thanks for your reply!

> You can use golang native method : https://golang.org/pkg/os/#LookupEnv
OK I will modify source code using this method.

> Don't forgot to update according tests in consequence 😉
I got it!

Plase wait a while, I will modify it and then get you back!
