### ISSUE TITLE
UX improvement

### ISSUE THREAD

**Issue by anjuls** [cloudskiff/driftctl#55]
**Description**
Usually, an AWS account is shared with multiple teams and projects so I don't think the `driftctl` is useful if just try to compare drift with a single TF state file.  It doesn't give a useful result.  Unless the whole infrastructure is governed by Terraform and driftctl can use multiple TF statefiles, it will be useful but such things are not really practical in my view.

**Comment by sjourdan** [comment]
Thank you @anjuls for taking the time for this feedback!

You're right, for the rest of us with many terraform states, issue #50 is very important. The good news is: we'll be working on it very soon as it's a top priority for us, too. 

If I understand well your use case, you have many teams sharing the same AWS account, with only some teams using Terraform. This makes driftctl output mostly pointless, probably because there are way too many "unmanaged" resources displayed.

Would it be useful for you: 

- to be able to monitor only resources from the state(s) (but you'll miss most unwanted changes)
or
- to be able to automatically save in some kind of tfstate AWS resources that aren't in your tfstates, and ignore them, so you can start "fresh", detecting changes from this day on
