### ISSUE TITLE
Please add an error report on the output.json 

### ISSUE THREAD

**Issue by AzySir** [cloudskiff/driftctl#640]
**Description**

Have a error report in the output.json that shows a .tfstate file or a bucket did not exist

A block like below?

**Example**
```
"failed_scans": [{
     "name":  "mystate-tf-state"
     "error": ".tfstate file does not exist"  
     "skipped": "yes" # This flag would show whether or not the error was accepted and skipped
  },
  {
     "name":  "mystate-bucket"
     "error": "mystate-bucket does not exist!"
     "skipped": "yes"
  }
]
```

**Problem Statement?**

This will assist with any schedulers running that might want to give a report so that development teams aren't running scheduled/automatic scans blindly. At the moment devs running this need to add their own logic (try/catch statements, if contains statements) in where as a simple error report will add more confidence, reliability and save that extra lifting by devs.

**Comment by AzySir** [comment]
Another error that I have found is a `400 AccessDenied - Unauthorized` on some resources.

This should also be as part of the report and this should **not** fail the whole scan.

**Comment by eliecharra** [comment]
> Another error that I have found is a 400 AccessDenied - Unauthorized on some resources.

@AzySir Can you detail us exactly your case ? Which resources are returning a 400 with access denied error ?
Actually amazon does not respect HTTP status code semantic, so we have to handle theses 400 usecase manually ...
Can you open a separate issue with theses cases ? This is not related to the original topic of this issue.

> Have a error report in the output.json that shows a .tfstate file or a bucket did not exist

It mean that you accept a driftctl output that is potentially broken (a lot of unmanaged resources due to missing state) ? Can you explain us your usecase more in details ? Actually we enforced the failure if one of the provided state cannot be read to avoid to get an inconsistent output.

**Comment by AzySir** [comment]
Hi @eliecharra someone else is having the 400 issue at - https://github.com/cloudskiff/driftctl/issues/665

**Comment by eliecharra** [comment]
> @AzySir Can you detail us exactly your case ? Which resources are returning a 400 with access denied error ?
> Actually amazon does not respect HTTP status code semantic, so we have to handle theses 400 usecase manually ...
> Can you open a separate issue with theses cases ? This is not related to the original topic of this issue.

Opened an issue here #666

**Comment by eliecharra** [comment]
Closing since first issue description will be handled by #697 and error on resources will be handled in #666.
