### ISSUE TITLE
RFC: Resource `Type` and `Id` immutability

### ISSUE THREAD

**Issue by eliecharra** [cloudskiff/driftctl#937]
# Status

**FEEDBACK REQUESTED**

# Problem

Following https://github.com/cloudskiff/driftctl/pull/928, we were wondering if it can be valuable to have `Id` and `Type` immutable for resources. If one of theses fields change we can consider it is a new resource. 

It can be dangerous to keep these fields public, as we use id and type to match ID between them it can lead us to unexpected behavior if by mistake we mutate theses fields.

It can be nice to have better getter naming too since `resource.ResourceId()` and `resource.ResourceType()` sounds redundant.

# Proposers

- @eliecharra 
- @sundowndev 
- @wbeuil 

# Record of votes

# Proposal

The final goal is to end with a Resource struct with unexported `Id` and `Type` fields and only getters.
Beside this we also want to have a new func `NewResource(id, ty string) *Resource`.
We also accept setter for other fields.

```go
type Resource struct {
	id, ty     string
        Attrs  *Attributes
	// Other fields below ...
}

func NewResource(id, ty string) *Resource {
	return &Resource{
		id:   id,
		ty: ty,
	}
}

func (r *Resource) Id() string {
	return r.id
}

func (r *Resource) Type() string {
	return r.ty
}

func (r *Resource) SetAttributes(attrs *Attributes) *Resource {
        r.Attrs = attrs
	return r
}
```

We can achieve this in **3 steps**:

### 1 - Replace struct initializations with `NewResource`

The first step here is to update each part of the code that is creating a resource manually.

```go
// Example taken from a test
stateResources: []*resource.Resource{
  &resource.Resource{
	Id:   "fake",
	Type: "FakeResource",
	Attrs: &resource.Attributes{
		"foobar": "barfoo",
	},
  },
},
// The code above should be updated to
stateResources: []*resource.Resource{
  resource.NewResource("fake", "FakeResource").
    SetAttributes(&resource.Attributes{
      "foobar": "barfoo",
    }),
},
```

### 2 - Use getters instead of direct field access

We should replace every occurrence of direct field access to a getter, only for `Id` and `Type` fields.

```go
return errors.Errorf("No arn found for resource %s (%s)", topic.Id, topic.Type)
// Should be changed to
return errors.Errorf("No arn found for resource %s (%s)", topic.ResourceId(), topic.ResourceType())
```

### 3 - Make Id and Type unexported and handle places where we do mutations

We should now unexport theses fields and change place we were doing modification on them. We should create new resource instead of mutate existing one

# Risk and Impact

The risk is to forgot to set resource fields when creating a new resource from an existing one.

Let's take an example, we want to change an `Id` for a given resource.

```go
newResource := resource.NewResource("new-id", oldResource.ResourceType()).SetAttributes(oldResource.Attributes())
// What if I forgot to set the schema or the source ? It may lead to unexpected behavior too
```

Should we provide a method to clone an existing resource which will encapsulate the logic of cloning a resource ?

**Comment by sundowndev** [comment]
Shouldn't we plan to unexport `Attrs` field too ?

```go
type Resource struct {
	id, ty     string
        attrs  *Attributes
	// Other fields below ...
}
```

**Comment by eliecharra** [comment]
> Shouldn't we plan to unexport `Attrs` field too ?
> 
> ```go
> type Resource struct {
> 	id, ty     string
>         attrs  *Attributes
> 	// Other fields below ...
> }
> ```

Why would we want to make it unexported since we can mutate it in any way ?

**Comment by sundowndev** [comment]
@eliecharra So we avoid having the same issue later and make every mutations using setters and access using getters. I think it's great to use methods instead of exporting struct's fields so we can disallow mutation on some fields, add extra logic to mutations and avoid big refactors like this one. WDYT ?

**Comment by moadibfr** [comment]
I think having a method to get the attribute has little sense since it won't prevent mutation. To prevent mutation we should return a copy and that would be an unnecessary cost.

Also we decided we wanted it to be mutable when we discussed if we should have an attribute map of the cty value. So I think I like having it exported so It's clear that it's mutable.

> The risk is to forgot to set resource fields when creating a new resource from an existing one.

I'm used to force all required field to be present in constructor. I would prefer attribute to be present in the New function (and have a setter to override if needed). And a clone method to have a clone with the same fields but only some overriden.

> Should we provide a method to clone an existing resource which will encapsulate the logic of cloning a resource ?

I think we should if we need this. It would provide a way to share the logic (like the full copy of attributes map) and it's always handy.
