### ISSUE TITLE
Update the Testing.md documentation to match how actual testing is done

### ISSUE THREAD

**Issue by OrenLeung** [cloudskiff/driftctl#948]
https://github.com/cloudskiff/driftctl/blob/main/docs/testing.md

Update the `MatchBy` multiple call documentation
![image](https://user-images.githubusercontent.com/47992694/131064951-79fab5b3-84cf-4b04-af1b-ad94e29f1c44.png)

In the current version, the `mockCalled` flag pattern is not used.

https://github.com/cloudskiff/driftctl/blob/main/pkg/remote/aws/repository/ec2_repository_test.go#L367

there is no `mockCalled` flag

**Comment by eliecharra** [comment]
This is a workaround for mockery logic, AWS return us a callback so this is a hack to mock it properly. So we use a `mock.MatchedBy` to be able to run a callback but `mock.MatchedBy` is not designed for this initially and so this is evaluated every time whether the mock has `.Once()` directive and is already called.

For the example you inlined (`ec2_repository_test`) this is not required since we mock the call only once, in the doc we say : `If you have several mocks on the same method`. You can check here an example https://github.com/cloudskiff/driftctl/blob/main/pkg/remote/aws/repository/iam_repository_test.go#L411

Note for maintainer : quote a real example in the doc (check the link on `iam_repository_test.go` above)
